FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src

COPY ["src/AppointmentService.Api/AppointmentService.Api.csproj", "src/AppointmentService.Api/"]
COPY ["src/AppointmentService.Application/AppointmentService.Application.csproj", "src/AppointmentService.Application/"]
COPY ["src/AppointmentService.Domain/AppointmentService.Domain.csproj", "src/AppointmentService.Domain/"]
COPY ["src/AppointmentService.Infrastructure/AppointmentService.Infrastructure.csproj", "src/AppointmentService.Infrastructure/"]

RUN dotnet restore "src/AppointmentService.Api/AppointmentService.Api.csproj"

COPY . .

WORKDIR "/src/src/AppointmentService.Api"
RUN dotnet build "AppointmentService.Api.csproj" -c "$BUILD_CONFIGURATION" -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "AppointmentService.Api.csproj" -c "$BUILD_CONFIGURATION" -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final
WORKDIR /app
COPY --from=publish /app/publish .
EXPOSE 8080
ENTRYPOINT ["dotnet", "AppointmentService.Api.dll"]