// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PatientService.Infrastructure.Persistence.Contexts;

#nullable disable

namespace PatientService.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PatientService.Domain.Entities.Customer", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier")
                    .HasColumnName("PatientId");

                b.Property<DateOnly?>("BirthDate")
                    .HasColumnType("date")
                    .HasColumnName("BirthDate");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime");

                b.Property<string>("CreatedBy")
                    .HasMaxLength(255)
                    .IsUnicode(false)
                    .HasColumnType("varchar(255)");

                b.Property<DateTime?>("DeletedAt")
                    .HasColumnType("datetime");

                b.Property<string>("DeletedBy")
                    .HasMaxLength(255)
                    .IsUnicode(false)
                    .HasColumnType("varchar(255)");

                b.Property<string>("Email")
                    .HasColumnType("varchar(100)")
                    .HasColumnName("Email");

                b.Property<string>("Gender")
                    .HasColumnType("varchar(10)")
                    .HasColumnName("Gender");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("bit");

                b.Property<bool>("IsMailVerified")
                    .HasColumnType("bit");

                b.Property<bool>("IsPhoneVerified")
                    .HasColumnType("bit");

                b.Property<DateTime?>("LastModifiedAt")
                    .HasColumnType("datetime");

                b.Property<string>("LastModifiedBy")
                    .HasMaxLength(255)
                    .IsUnicode(false)
                    .HasColumnType("varchar(255)");

                b.Property<string>("LastName")
                    .IsRequired()
                    .HasMaxLength(255)
                    .IsUnicode(false)
                    .HasColumnType("varchar(80)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(80)
                    .IsUnicode(false)
                    .HasColumnType("varchar(80)");

                b.Property<string>("Phone")
                    .HasColumnType("varchar(50)")
                    .HasColumnName("PhoneNumber");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasColumnType("varchar(20)");

                b.HasKey("Id")
                    .HasName("PK_Patient");

                b.ToTable("Patient", "Patient");
            });

            modelBuilder.Entity("PatientService.Domain.Entities.CustomerAddress", b =>
            {
                b.Property<Guid>("Id")
                    .HasColumnType("uniqueidentifier")
                    .HasColumnName("PatientAddressId");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime");

                b.Property<string>("CreatedBy")
                    .HasMaxLength(255)
                    .IsUnicode(false)
                    .HasColumnType("varchar(255)");

                b.Property<Guid>("PatientId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTime?>("DeletedAt")
                    .HasColumnType("datetime");

                b.Property<string>("DeletedBy")
                    .HasMaxLength(255)
                    .IsUnicode(false)
                    .HasColumnType("varchar(255)");

                b.Property<bool>("IsDefault")
                    .HasColumnType("bit");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("bit");

                b.Property<string>("Label")
                    .IsRequired()
                    .HasMaxLength(30)
                    .IsUnicode(false)
                    .HasColumnType("varchar(30)")
                    .HasColumnName("Label");

                b.Property<DateTime?>("LastModifiedAt")
                    .HasColumnType("datetime");

                b.Property<string>("LastModifiedBy")
                    .HasMaxLength(255)
                    .IsUnicode(false)
                    .HasColumnType("varchar(255)");

                b.HasKey("Id")
                    .HasName("PK_PatientAddress");

                b.HasIndex("PatientId");

                b.ToTable("PatientAddress", "Patient");
            });

            modelBuilder.Entity("PatientService.Domain.Entities.Customer", b =>
            {
                b.OwnsOne("PatientService.Domain.ValueObjects.DocumentId", "Document", b1 =>
                {
                    b1.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b1.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("DocumentNumber");

                    b1.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(12)")
                        .HasColumnName("DocumentType");

                    b1.HasKey("PatientId");

                    b1.ToTable("Patient", "Patient");

                    b1.WithOwner()
                        .HasForeignKey("PatientId");
                });

                b.Navigation("Document")
                    .IsRequired();
            });

            modelBuilder.Entity("PatientService.Domain.Entities.CustomerAddress", b =>
            {
                b.HasOne("PatientService.Domain.Entities.Customer", "Customer")
                    .WithMany("Address")
                    .HasForeignKey("PatientId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("FK_PatientAddress_Patient");

                b.OwnsOne("PatientService.Domain.ValueObjects.AddressVo", "Address", b1 =>
                {
                    b1.Property<Guid>("CustomerAddressId")
                        .HasColumnType("uniqueidentifier");

                    b1.Property<string>("Departament")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Departament");

                    b1.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("District");

                    b1.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Province");

                    b1.Property<string>("Reference")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Reference");

                    b1.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Street");

                    b1.HasKey("CustomerAddressId");

                    b1.ToTable("PatientAddress", "Patient");

                    b1.WithOwner()
                        .HasForeignKey("CustomerAddressId");
                });

                b.Navigation("Address")
                    .IsRequired();

                b.Navigation("Customer");
            });

            modelBuilder.Entity("PatientService.Domain.Entities.Customer", b =>
            {
                b.Navigation("Address");
            });
#pragma warning restore 612, 618
        }
    }
}